async(page)=>{
  const results=[];const check=(name,pass)=>results.push({name,pass:!!pass});
  page.setDefaultTimeout(5000);
  await page.route('**/*',r=>r.continue());
  await page.setViewportSize({width:1600,height:600});
  await page.goto('http://127.0.0.1:4321/rwd-preview.html?lang=zh-TW');
  const groups=await page.locator('#preset optgroup').evaluateAll(groups=>groups.filter(g=>g.label.includes('8')).map(g=>({brand:g.label,count:new Set([...g.children].map(o=>o.dataset.model)).size})));
  check('three brands each have eight distinct models',groups.length===3&&groups.every(g=>g.count===8));
  const models=await page.locator('#preset option[data-size]').evaluateAll(options=>options.map(o=>({value:o.value,size:o.dataset.size})));
  let sizesPass=true;
  for(const model of models){await page.locator('#preset').selectOption(model.value);const actual=await page.locator('#preview').evaluate(n=>[n.clientWidth,n.clientHeight].join(','));sizesPass&&=actual===model.size;}
  check('every device display preset applies its declared viewport',sizesPass);
  check('redundant Apply button removed',await page.locator('#sizes button[type=submit]').count()===0);
  await page.locator('#brand').selectOption('1');
  check('brand filters model groups without changing the viewport',await page.locator('#preset optgroup:not([hidden])').count()===1);
  await page.locator('#preset').selectOption('iphone-16-8');
  check('model selection applies immediately',await page.locator('#preview').evaluate(n=>n.clientWidth===393&&n.clientHeight===852));
  await page.locator('#width').fill('777');await page.locator('#height').focus();
  check('custom width applies on leaving the input',await page.locator('#preview').evaluate(n=>n.clientWidth===777));
  await page.locator('#height').fill('999');await page.locator('#height').press('Enter');
  check('custom height applies on Enter',await page.locator('#preview').evaluate(n=>n.clientHeight===999));
  await page.locator('#width').fill('10');await page.locator('#height').focus();
  check('invalid custom size preserves last valid viewport',await page.locator('#preview').evaluate(n=>n.clientWidth===777));
  await page.locator('#width').fill('777');await page.locator('#height').focus();
  await page.locator('#rotate').click();
  check('rotate applies both dimensions immediately',await page.locator('#preview').evaluate(n=>n.clientWidth===999&&n.clientHeight===777));
  await page.locator('#brand').selectOption('all');
  await page.locator('#preset').selectOption('768,1024');
  await page.locator('.stage').hover();
  const panel=page.locator('[data-inspector-external]');
  await panel.locator('.tree').waitFor();
  check('hovering preview starts inspector without launch click',await panel.count()===1);
  check('embedded demo hides duplicate launch button',!await page.frameLocator('#preview').locator('#start-inspector').isVisible());
  const preview=page.frameLocator('#preview');
  const report=panel.locator('[aria-label="AI locator report"]');
  check('category slider stays one row',await panel.locator('[role=tab]').evaluateAll(nodes=>new Set(nodes.map(n=>Math.round(n.getBoundingClientRect().top))).size===1));
  check('only active category displayed',await panel.locator('[role=tabpanel]:visible').count()===1);
  check('DOM structure available immediately',await panel.locator('.tree').isVisible());
  check('panel outside target document',await preview.locator('.panel').count()===0);
  check('panel does not overlap frame',await page.evaluate(()=>{
    const a=document.querySelector('#preview').getBoundingClientRect(),b=document.querySelector('.side').getBoundingClientRect();return a.right<=b.left;
  }));
  check('step 1 explains click vs hover and blocks empty next',await panel.getByText(/Step 1 ·/).isVisible()&&await panel.getByRole('button',{name:'下一步：確認範圍 →',exact:true}).isDisabled());
  const mainName=panel.locator('.tree-name').filter({hasText:'main#demo-main'});
  await mainName.hover();
  check('hover leaves RWD settings open',await page.locator('#sizes').isVisible());
  await mainName.click();
  check('DOM selection collapses RWD without changing dimensions',!await page.locator('#sizes').isVisible()&&await page.locator('#preview').evaluate(n=>n.clientWidth===768&&n.clientHeight===1024));
  const beforeExpand=await report.inputValue();
  await panel.getByRole('button',{name:'展開／收合 section.grid',exact:true}).click();
  check('arrow expands without changing selection',beforeExpand===await report.inputValue());
  await panel.locator('.tree-name').filter({hasText:'article.card'}).first().hover();
  const treeScroll=await panel.locator('.tree').evaluate(n=>n.scrollTop);
  const panelTop=await panel.locator('.tree').evaluate(n=>n.getBoundingClientRect().top);
  check('tree hover previews corresponding page element',await preview.locator('.hover-target').isVisible()&&(await preview.locator('.label').innerText()).includes('article.card'));
  await panel.locator('.tree-name').filter({hasText:'article.card'}).first().click();
  check('tree click preserves panel position and scroll',await panel.locator('.tree').evaluate((n,old)=>n.scrollTop===old.scroll&&Math.abs(n.getBoundingClientRect().top-old.top)<1,{scroll:treeScroll,top:panelTop}));
  check('one selected layer marked',await panel.locator('.tree-name[aria-pressed="true"]').count()===1);
  check('no resume picking button',await panel.getByRole('button',{name:'選其他元素',exact:true}).count()===0);
  const name=panel.locator('.tree-name').filter({hasText:'article.card'}).first();
  await name.focus();await name.press('ArrowDown');
  check('down key moves focus to next layer',await panel.locator('.tree-name').filter({hasText:'article.card'}).nth(1).evaluate(n=>n.getRootNode().activeElement===n));
  await name.focus();await name.press('ArrowRight');
  check('right key expands child layer',await panel.locator('.tree-name').filter({hasText:'div.art'}).first().isVisible());
  check('RWD controls are inside the external panel',await page.locator('.side .rwd-controls').count()===1);
  if(!await page.locator('#sizes').isVisible())await page.locator('.rwd-controls > summary').click();
  await page.locator('.rwd-controls > summary').click();
  check('RWD controls collapse to summary',!await page.locator('#sizes').isVisible());
  await page.locator('.rwd-controls > summary').click();
  check('RWD controls fit their panel without horizontal scrolling',await page.locator('.toolbar').evaluate(n=>n.scrollWidth<=n.clientWidth));
  check('workspace fills current window and preserves test viewport',await page.evaluate(()=>{
    const frame=document.querySelector('#preview'),stage=document.querySelector('.stage');
    const f=frame.getBoundingClientRect(),a=stage.getBoundingClientRect();
    return Math.abs(document.body.getBoundingClientRect().height-innerHeight)<1 && f.top>=a.top && f.bottom<=a.bottom && frame.contentWindow.innerWidth===768 && frame.contentWindow.innerHeight===1024;
  }));
  const held=await report.inputValue();
  if(!await page.locator('#sizes').isVisible())await page.locator('.rwd-controls > summary').click();
  check('RWD can reopen after selection',await page.locator('#sizes').isVisible());
  await preview.locator('h1').evaluate(n=>n.scrollIntoView({block:'center'}));
  const hoverBox=await preview.locator('h1').boundingBox();
  await page.mouse.move(hoverBox.x+hoverBox.width/2,hoverBox.y+hoverBox.height/2);
  await page.waitForFunction(()=>document.querySelector('#preview').contentDocument.querySelector('[data-workflow-inspector]').shadowRoot.querySelector('.label').textContent.includes('h1'));
  check('hover another element keeps selected report',held===await report.inputValue());
  check('hover name and separate outline displayed',await preview.locator('.hover-target').isVisible());
  check('hover after reopening does not recollapse RWD',await page.locator('#sizes').isVisible());
  await page.mouse.click(hoverBox.x+hoverBox.width/2,hoverBox.y+hoverBox.height/2);
  check('page selection recollapses manually reopened RWD',!await page.locator('#sizes').isVisible());
  check('page click syncs selected layer',await panel.locator('.tree-name[aria-pressed="true"]').innerText().then(t=>t.includes('h1')));
  await panel.locator('.tree-name').filter({hasText:'article.card'}).first().click();
  check('tree selection highlights preview',await preview.locator('[data-workflow-inspector] .selected').isVisible());
  check('tree selects matching component group',await preview.locator('[data-workflow-inspector] .match').count()===2);
  await panel.getByRole('button',{name:'下一步：確認範圍 →',exact:true}).click();
  check('step 1 next opens step 2 with selected target',await panel.getByText(/Step 2 ·/).isVisible()&&(await panel.locator('.selection-hint').textContent()).includes('article.card'));
  await panel.getByRole('button',{name:'同 class .card',exact:true}).click();
  check('all class instances counted', (await panel.locator('[aria-label^="目前頁面匹配數量"]').textContent()).includes('共 3'));
  await panel.getByRole('button',{name:'↓ 下一個',exact:true}).click();
  const first=await report.inputValue();
  await panel.getByRole('button',{name:'↓ 下一個',exact:true}).click();
  check('next selects different instance',first!==await report.inputValue());
  await panel.getByRole('button',{name:'↑ 上一個',exact:true}).click();
  check('previous returns to first',first===await report.inputValue());
  await panel.getByText('例外：哪些不要修改？ / Exclude instances',{exact:true}).click();
  await panel.getByRole('checkbox').nth(1).check();
  check('exception changes outline',await preview.locator('[data-workflow-inspector] .match.excluded').count()===1);
  await panel.getByRole('button',{name:'下一步：寫需求 →',exact:true}).click();
  check('step 2 next opens step 3',await panel.getByText(/Step 3 ·/).isVisible());
  await panel.getByRole('textbox',{name:'你想怎麼改？ / Your requested change',exact:true}).fill('Change included cards to orange.');
  await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.__batchCopy=text;}}}));
  await panel.getByRole('button',{name:'複製修改需求',exact:true}).click();
  check('copy gives explicit next action', (await panel.locator('.status').textContent()).includes('切到 AI 對話'));
  await panel.getByRole('button',{name:'← 回到確認範圍',exact:true}).click();
  check('back retains exception',await panel.getByRole('checkbox').nth(1).isChecked());
  await panel.getByRole('button',{name:'下一步：寫需求 →',exact:true}).click();
  check('return retains typed request',(await panel.getByRole('textbox',{name:'你想怎麼改？ / Your requested change',exact:true}).inputValue())==='Change included cards to orange.');
  const copied=await page.evaluate(()=>window.__batchCopy);
  check('combined copy contains request, match and exclusion',copied.includes('Change included cards to orange.')&&copied.includes('Match: .card')&&copied.includes('例外不修改 / Exclude:')&&copied.includes('article:nth-of-type(2)'));
  check('copy include section excludes exception',!copied.split('要修改 / Include:')[1].split('例外不修改')[0].includes('article:nth-of-type(2)'));
  // The button lives in the outer document: a blocked iframe must not receive its write.
  await preview.locator('body').evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{window.__wrongCopy=true;throw new DOMException('Synthetic inner denial','NotAllowedError');}}}));
  await panel.getByRole('button',{name:'複製修改需求',exact:true}).click();
  check('outer panel uses owner window, never inspected iframe clipboard',await page.evaluate(()=>!!window.__batchCopy)&&!await preview.locator('body').evaluate(()=>window.__wrongCopy));
  await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw new DOMException('Synthetic outer denial','NotAllowedError');}}}));
  await panel.getByRole('button',{name:'複製修改需求',exact:true}).click();
  const manual=panel.locator('[aria-label="手動複製完整修改單 / Manual copy"]');
  await manual.waitFor({state:'visible'});
  check('denied write selects entire manual report in its owning document',await manual.evaluate(n=>n.getRootNode().activeElement===n&&n.selectionStart===0&&n.selectionEnd===n.value.length&&n.value.length>0));
  check('denied write preserves request and explains keyboard next step',(await panel.getByRole('textbox',{name:'你想怎麼改？ / Your requested change',exact:true}).inputValue())==='Change included cards to orange.'&&(await panel.locator('.status').innerText()).includes('需求沒有遺失'));
  check('manual report retains exact requested scope and exceptions',await manual.inputValue()===copied);
  await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:undefined}));
  await panel.getByRole('button',{name:'複製元素位置',exact:true}).click();
  check('missing Clipboard API still selects locator for manual copy',await manual.isVisible()&&(await manual.inputValue()).includes('article:nth-of-type('));
  await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.__batchCopy=text;}}}));
  await panel.getByRole('button',{name:'複製修改需求',exact:true}).click();
  check('successful retry clears manual fallback',!await manual.isVisible()&&(await panel.locator('.status').innerText()).includes('已複製'));
  if(!await page.locator('#sizes').isVisible())await page.locator('.rwd-controls > summary').click();
  await page.locator('#fit').click();
  check('100 percent preserves layout dimensions',await preview.locator('body').evaluate(()=>innerWidth===768&&innerHeight===1024));
  await page.locator('#fit').click();
  if(!await page.locator('#sizes').isVisible())await page.locator('.rwd-controls > summary').click();
  await page.locator('.more > summary').click();
  check('settings opens',await page.locator('.more-content').isVisible());
  await page.locator('.more > summary').press('Escape');
  check('Escape closes settings',!await page.locator('.more-content').isVisible());
  await page.setViewportSize({width:390,height:600});
  check('mobile size controls and document do not overflow',await page.evaluate(()=>document.querySelector('.toolbar').scrollWidth<=document.querySelector('.toolbar').clientWidth&&document.documentElement.scrollWidth<=390&&document.body.getBoundingClientRect().height<=600));
  check('narrow screen panel below preview',await page.evaluate(()=>{
    const a=document.querySelector('.stage').getBoundingClientRect(),b=document.querySelector('.side').getBoundingClientRect();return b.top>=a.bottom;
  }));
  await page.setViewportSize({width:1280,height:900});
  check('tall viewport is filled beyond former 600px cap',await page.evaluate(()=>Math.abs(document.body.getBoundingClientRect().height-innerHeight)<1));
  const footerBefore=await panel.locator('#inspector-view-2 .step-footer').boundingBox();
  await panel.locator('#inspector-view-2 .view-body').evaluate(n=>n.scrollTop=n.scrollHeight);
  const footerAfter=await panel.locator('#inspector-view-2 .step-footer').boundingBox();
  check('copy action stays fixed while context scrolls',Math.abs(footerBefore.y-footerAfter.y)<1&&footerAfter.y+footerAfter.height<=900);
  await page.locator('.more > summary').click();
  await page.getByText('換成自己的本機預覽 / Use your local preview',{exact:true}).click();
  await page.locator('#load').click();
  check('unsafe load shows visible explanation',await page.locator('#rwd-feedback').isVisible()&&(await page.locator('#rwd-feedback').innerText()).includes('Confirm the safety gates'));
  await page.locator('.more > summary').press('Escape');
  await page.setViewportSize({width:640,height:300});
  check('short window keeps an explicit close control',await panel.getByRole('button',{name:'關閉 ×',exact:true}).isVisible());
  await panel.getByRole('button',{name:'關閉 ×',exact:true}).click();
  check('closing restores UI Inspect launch button',await page.locator('#inspect').isVisible());
  check('close removes both control and overlay',await panel.count()===0&&await preview.locator('[data-workflow-inspector]').count()===0);
  await page.locator('.stage').hover();await panel.locator('.tree').waitFor();
  check('returning to preview after close reactivates without launch click',await panel.count()===1);
  await panel.getByRole('button',{name:'關閉 ×',exact:true}).click();
  await page.setViewportSize({width:390,height:844});
  let releaseDemo;
  const delayedDemo=new Promise(resolve=>{releaseDemo=resolve;});
  await page.route('**/demo.html',async route=>{await delayedDemo;await route.continue();});
  await page.goto('http://127.0.0.1:4321/rwd-preview.html?lang=zh-TW',{waitUntil:'domcontentloaded'});
  await page.locator('.stage').hover();releaseDemo();
  await panel.locator('.tree').waitFor();
  check('hover before iframe load opens exactly one working panel',await panel.count()===1&&await panel.locator('.tree-name').count()>0);
  check('narrow initial window starts with collapsible RWD summary',!await page.locator('#sizes').isVisible());
  check('narrow initial DOM tree has usable visible space',await panel.locator('.tree').evaluate(n=>n.getBoundingClientRect().height>=80));
  await page.locator('.rwd-controls > summary').click();
  check('narrow window can expand size controls explicitly',await page.locator('#sizes').isVisible());
  await page.unroute('**/demo.html');
  await page.setViewportSize({width:1280,height:900});
  await preview.locator('body').evaluate(()=>{
    const style=document.createElement('style');style.textContent=':root{--sample-ink:#123456;--private-unused:DO-NOT-COLLECT}.card{color:var(--sample-ink)}@media(min-width:9000px){.card{padding:var(--inactive)}}';document.head.append(style);
  });
  await panel.getByRole('button',{name:'展開／收合 section.grid',exact:true}).click();
  await panel.locator('.tree-name').filter({hasText:'article.card'}).first().click();
  check('CSS variable reference found without copying arbitrary values',(await report.inputValue()).includes('color ← --sample-ink')&&!(await report.inputValue()).includes('DO-NOT-COLLECT')&&!(await report.inputValue()).includes('--inactive'));
  check('CSS shorthand variable references are not lost by CSSOM expansion',(await report.inputValue()).includes('padding ← --card-space')&&(await report.inputValue()).includes('background ← --card-surface'));
  await panel.locator('[role=tab]').nth(1).click();await panel.getByRole('button',{name:'同 class .card',exact:true}).click();
  const rail=page.locator('.match-rail');
  check('number rail matches current group',await rail.getByRole('button').count()===3);
  await rail.getByRole('button').nth(2).click();
  check('number 3 jumps to corresponding selection',await rail.getByRole('button').nth(2).getAttribute('aria-current')==='true'&&(await report.inputValue()).includes('article:nth-of-type(3)'));
  check('selected element has matching numbered badge',(await preview.locator('.selected .element-number').innerText()).includes('#3'));
  await panel.locator('[role=tab]').nth(1).click();await panel.locator('.exception-details > summary').click();await panel.getByRole('checkbox').nth(1).check();
  check('excluded number has distinct rail marker',await rail.locator('button.excluded').innerText()==='2');
  await rail.getByRole('combobox').selectOption('copy');
  check('copy-only tick list hides excluded item and keeps stable numbers',await rail.getByRole('button').count()===2&&await rail.getByRole('button').last().innerText()==='3');
  await rail.getByRole('combobox').selectOption('all');
  check('matches tick list restores all items',await rail.getByRole('button').count()===3);
  await panel.locator('[role=tab]').nth(2).click();await panel.getByRole('textbox',{name:'你想怎麼改？ / Your requested change',exact:true}).fill('Make #3 orange, keep #2.');
  await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{}}}));
  await panel.getByRole('button',{name:'複製修改需求',exact:true}).click();
  check('successful copy shows notification',await page.locator('[data-inspector-external] .copy-toast').isVisible());
  await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw Error('synthetic denial');}}}));
  await panel.getByRole('button',{name:'複製修改需求',exact:true}).click();
  check('failed copy never shows success notification',!await page.locator('[data-inspector-external] .copy-toast').isVisible());
  await panel.locator('[role=tab]').nth(1).click();await panel.getByRole('button',{name:'清除同類框線',exact:true}).click();
  check('empty tick list is hidden',!await rail.isVisible());
  await page.goto('http://127.0.0.1:4321/demo.html');
  await page.locator('#start-inspector').click();
  await page.waitForURL('**/rwd-preview.html?*');
  await page.locator('.stage').hover();await panel.locator('.tree').waitFor();
  check('standalone demo opens external workspace instead of floating panel',await panel.count()===1&&await page.frameLocator('#preview').locator('#start-inspector').isHidden());
  check('automatic language choice visibly says Language',await panel.locator('select option[value=auto]').textContent()==='語言 / Language');
  check('exceptions have a prominent border and large target',await panel.locator('.exception-details > summary').evaluate(n=>getComputedStyle(n).borderTopWidth==='2px'&&getComputedStyle(n).fontWeight==='700'));
  const treeToggle=panel.locator('.tree-toggle[aria-expanded]').first();
  await treeToggle.click();await treeToggle.click();
  check('DOM disclosure keeps its larger SVG after repeated toggles',await treeToggle.locator('svg').evaluate(n=>n.getBoundingClientRect().width===20));
  const rwdSummary=page.locator('.rwd-controls > summary');
  check('RWD disclosure is a full row target with a large right icon',await rwdSummary.evaluate(n=>{
    const row=n.getBoundingClientRect(),icon=n.querySelector('svg').getBoundingClientRect();
    return row.height>=44&&icon.width===24&&row.right-icon.right<25;
  }));
  if(!await page.locator('#rotate').isVisible())await rwdSummary.click();
  check('rotate has a 44px hit target and 22px icon',await page.locator('#rotate').evaluate(n=>n.getBoundingClientRect().width===44&&n.getBoundingClientRect().height===44&&n.querySelector('svg').getBoundingClientRect().width===22));
  const headingBefore=await panel.locator('.tree-name').count();
  await panel.getByRole('button',{name:'更新圖層',exact:true}).click();
  check('icon-only refresh still rebuilds usable layers',await panel.locator('.tree-name').count()===headingBefore);
  await panel.getByRole('button',{name:'收合面板',exact:true}).click();
  check('icon-only collapse hides panel and exposes reopen',!await panel.locator('.panel').isVisible()&&await panel.getByRole('button',{name:'詳情 / Details',exact:true}).isVisible());
  await panel.getByRole('button',{name:'詳情 / Details',exact:true}).click();
  check('collapsed panel can reopen',await panel.locator('.panel').isVisible());
  return {results,passed:results.filter(r=>r.pass).length,failed:results.filter(r=>!r.pass).length};
}
